apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "fullname" . }}
  namespace: {{ .Values.Namespace | default "default" }}
type: Opaque
data:
  {{- if .Values.AdminPassword }}
  grafana-admin-password: {{ .Values.AdminPassword | b64enc | quote }}
  {{- else }}
  grafana-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  grafana-admin-user: {{ .Values.AdminUser | b64enc | quote }}
